### ISSUE TITLE
Unable to parse instagram profiles

### ISSUE THREAD

**Issue by michabirklbauer** [t0xic-m/instatools#5]
After too many requests/sometimes any valid instagram profile URL yields the login page instead and therefore JSON can't be loaded:
```python
ERROR loading json!
Expecting value: line 1 column 1 (char 0)
Full error traceback:
Traceback (most recent call last):
  File "C:\Python\Python38\lib\site-packages\InstaTools\__init__.py", line 232, in getUserID
    json_data = json.loads(data)
  File "C:\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
-1
```
Possibly have to change header again as referenced in #2 already - if it is even possible to bypass this limitation.

**Comment by michabirklbauer** [comment]
Minimizing profile requests by storing JSON object locally during session would be a good start, also better error message in case it still happens.

**Comment by michabirklbauer** [comment]
Update 16 April, 2021: Instagram profiles are not publicly available anymore. Unable to parse instagram profiles and/or posts without login -> package doesn't work.
